[package]
name = "burdbot"
version = "0.1.0"
authors = ["DELIBURD"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.4"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "time"] }
simple_logger = "1.11.0"
log = "0.4.14"
rusqlite = { version = "0.25.3", features = ["chrono", "bundled"] }
songbird = "0.1.6"
bimap = "0.6.1"
chrono = "0.4.19"
lazy_static = "1.4.0"
regex = "1.5.4"
simsearch = "0.2.3"