name: Setup burdbot workspace
description: Sets up burdbot's workspace, injecting a test key

inputs: {}
outputs: {}

runs:
  using: composite
  steps:
    - name: install toolchain after checkout
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: inject test key
      run: |
        echo "pub const AES_KEY: &str = \"\";" > $SECRET_FILE
      shell: bash
      env:
        SECRET_FILE: ./burdbot-macros/burdbot-macros-internal/src/secret.rs

    - name: install burdbot dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lynx
      shell: bash
        