[package]
name = "burdbot-macros-impl"
version = "0.1.0"
authors = ["DELIBURD"]
edition = "2024"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
burdbot-macros-internal = { version = "0.1", path = "../burdbot-macros-internal" }
syn = { version = "2", features = ["full", "fold"] }
