name: Burdbot audit workflow

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 00 * * *'

jobs:
  audit-project:
    name: Audits the project for rustsec advisories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Audit Burdbot dependencies
        uses: actions-rust-lang/audit@v1
        with:
          denyWarnings: true