name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  loc:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get SLOC
        run: sudo npm install -g sloc
      - name: Run SLOC
        run: sloc --keys source --details ./ 2>&1 | tee sloc.txt
      - uses: actions/upload-artifact@v2
        with:
          name: LOC
          path: sloc.txt
