name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get-repo-loc:
    name: gets the loc for the repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get SLOC
        run: sudo npm install -g sloc
      - name: Run SLOC
        run: sloc --keys source --details ./ 2>&1 | tee sloc.txt
      - uses: actions/upload-artifact@v4
        with:
          name: LOC
          path: sloc.txt
  build-lint-and-test:
    name: builds lints and tests the project
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: verify formatting of the workspace
        run: cargo fmt --all --check

      - name: build workspace
        run: cargo build --workspace --verbose

      - name: lint repo with clippy
        run: cargo clippy --workspace -- -D clippy::all -D warnings

      - name: build tests
        run: cargo test --workspace --no-run --verbose
      - name: run tests
        run: cargo test --workspace --verbose
